apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: firstapp
  template:
    matadata:
      name: firstapp
      labels:
        app: firstapp
    spec:
      containers:
        - name: first-nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80